// Code generated by `make copy-generate`; DO NOT EDIT.
package copykeys

const CompactRecruitmentMidT3 = "compact.recruitment.mid_t3"
const RouteRegistryFirstReordered = "route.registry_first_reordered"
