// Code generated by `make copy-generate`; DO NOT EDIT.
package copykeys

const CompactRecruitmentMidT3 = "compact.recruitment.mid_t3"
const RouteRegistryFirstReordered = "route.registry_first_reordered"

func All() []string { return []string{"category.any_percent", "category.ethical_percent", "category.hundred_percent", "category.low_percent", "category.valuation", "compact.recruitment.mid_t3", "incorporate.bootstrapper", "incorporate.enterprise", "incorporate.open_source", "incorporate.vc_funded", "resource.company_cash.cap.phase0", "route.registry_first_reordered", "soul.recovery.defrag.description", "soul.recovery.defrag.disclosure", "soul.recovery.defrag.reason", "soul.recovery.defrag.title", "soul.recovery.repot.description", "soul.recovery.repot.disclosure", "soul.recovery.repot.reason", "soul.recovery.repot.title", "soul.recovery.server_room.description", "soul.recovery.server_room.disclosure", "soul.recovery.server_room.reason", "soul.recovery.server_room.title"} }
