# syntax=docker/dockerfile:1.7@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e
FROM scratch

ARG RELEASE_VERSION
ARG SOURCE_COMMIT
LABEL org.opencontainers.image.title="Cloud Clicker gameserver" \
      org.opencontainers.image.version="${RELEASE_VERSION}" \
      org.opencontainers.image.revision="${SOURCE_COMMIT}" \
      org.opencontainers.image.source="https://github.com/stronk-dev/destroy-humanity-any-percent" \
      org.opencontainers.image.licenses="MIT"

COPY --chmod=0555 gameserver /usr/local/bin/gameserver
COPY --chown=65532:65532 content/ /opt/cloud-clicker/content/

USER 65532:65532
EXPOSE 8080
STOPSIGNAL SIGTERM
ENTRYPOINT ["/usr/local/bin/gameserver"]
