package formulas

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"cloud-clicker/server/commons"
	"cloud-clicker/server/economy"
	"cloud-clicker/server/multiplier"
	"cloud-clicker/server/publicapi"
)

func publishedArtifact(t *testing.T) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "docs", "generated", "production-formulas.json"))
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func TestPublishedFormulaModelAndDescriptorPreserveExistingBytes(t *testing.T) {
	data := publishedArtifact(t)
	before := bytes.Clone(data)
	if err := Validate(data); err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(data, before) {
		t.Fatal("validation modified historical bytes")
	}
	var artifact Artifact
	if err := json.Unmarshal(data, &artifact); err != nil {
		t.Fatal(err)
	}
	encoded, err := json.MarshalIndent(artifact, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(append(encoded, '\n'), data) {
		t.Fatal("extracted model changes generated bytes or field order")
	}
}

func TestFormulaDescriptorCoversNullableAndPopulatedOwnerArms(t *testing.T) {
	var artifact Artifact
	if err := json.Unmarshal(publishedArtifact(t), &artifact); err != nil {
		t.Fatal(err)
	}
	if artifact.AxisStack.Pinned != nil {
		t.Fatal("expected the current null pin fixture; retain separate null/populated coverage")
	}
	artifact.Commons.SourceWeights = []commons.SourceWeight{{SourceID: "upgrade.fixture", Slot: multiplier.SlotUpgrades, WeightPPM: 100_000, Forsworn: false}}
	for _, input := range []economy.AxisInput{economy.AxisInputAttainmentRun, economy.AxisInputScoreRun, economy.AxisInputCloutRun} {
		t.Run(string(input), func(t *testing.T) {
			artifact.AxisStack.Pinned = &AxisStackPinning{Input: string(input), InputCap: 100, CapReasonKey: "axis.fixture.cap", MaximumAtCapPPM: "1e2"}
			data, err := json.Marshal(artifact)
			if err != nil {
				t.Fatal(err)
			}
			if err := Validate(data); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestFormulaDescriptorRejectsMalformedArtifactWithoutReplacingBytes(t *testing.T) {
	type objectMap = map[string]any
	nested := func(root objectMap, key string) objectMap { return root[key].(objectMap) }
	populatedPin := func(root objectMap) objectMap {
		pin := objectMap{"input": string(economy.AxisInputScoreRun), "input_cap": 100, "cap_reason_key": "axis.fixture.cap", "maximum_product_at_cap": "1e2"}
		nested(root, "axis_stack")["pinned"] = pin
		return pin
	}
	for _, test := range []struct {
		name   string
		mutate func(objectMap)
	}{
		{"missing root field", func(v objectMap) { delete(v, "production_rate") }},
		{"extra root field", func(v objectMap) { v["private_note"] = "not declared" }},
		{"unsupported version", func(v objectMap) { v["schema_version"] = 15 }},
		{"missing nullable pin", func(v objectMap) { delete(nested(v, "axis_stack"), "pinned") }},
		{"open pin object", func(v objectMap) { nested(v, "axis_stack")["pinned"] = objectMap{"arbitrary": true} }},
		{"unsupported populated pin input", func(v objectMap) { populatedPin(v)["input"] = "lifetime_score" }},
		{"missing populated pin field", func(v objectMap) { delete(populatedPin(v), "input_cap") }},
		{"extra populated pin field", func(v objectMap) { populatedPin(v)["private_note"] = "extra" }},
		{"invalid populated pin decimal", func(v objectMap) { populatedPin(v)["maximum_product_at_cap"] = "Infinity" }},
		{"extra meter field", func(v objectMap) { nested(v, "meters")["private_note"] = "extra" }},
		{"missing meter field", func(v objectMap) { delete(nested(v, "meters"), "decay") }},
		{"null list", func(v objectMap) { nested(v, "commons")["source_weights"] = nil }},
		{"wrong source weight shape", func(v objectMap) { nested(v, "commons")["source_weights"] = []any{objectMap{"source_id": "fixture"}} }},
		{"unsupported source weight slot", func(v objectMap) {
			nested(v, "commons")["source_weights"] = []any{objectMap{"source_id": "fixture", "slot": "arbitrary", "forsworn": false, "weight_ppm": 1}}
		}},
		{"invalid decimal", func(v objectMap) { nested(v, "commons")["maximum_bonus"] = "NaN" }},
		{"noncanonical decimal", func(v objectMap) { nested(v, "commons")["maximum_bonus"] = "5" }},
		{"fractional int64", func(v objectMap) { nested(v, "guild")["stock_intake_cap"] = json.Number("1.5") }},
		{"integer encoded as decimal", func(v objectMap) { nested(v, "guild")["stock_intake_cap"] = json.Number("1.0") }},
		{"int64 overflow", func(v objectMap) { nested(v, "guild")["stock_intake_cap"] = json.Number("9223372036854775808") }},
		{"string instead of integer", func(v objectMap) { nested(v, "guild")["stock_intake_cap"] = "120" }},
		{"bad source fingerprint", func(v objectMap) { v["source_fingerprint"] = "unknown" }},
		{"unsupported slot", func(v objectMap) { v["multiplier_slot_order"] = []any{"arbitrary"} }},
		{"unsupported within-slot order", func(v objectMap) { v["within_slot_order"] = "unsorted" }},
		{"unsupported fallback arm", func(v objectMap) { nested(v, "minigame_scaling")["fallback_arms"] = []any{"cheating_bot"} }},
		{"extra synergy field", func(v objectMap) {
			nested(v, "purchasable_content")["synergy_pools"].([]any)[0].(objectMap)["arbitrary"] = true
		}},
		{"unsupported synergy curve", func(v objectMap) {
			nested(v, "purchasable_content")["synergy_pools"].([]any)[0].(objectMap)["curve"] = "exponential"
		}},
		{"unsupported synergy source", func(v objectMap) {
			pool := nested(v, "purchasable_content")["synergy_pools"].([]any)[0].(objectMap)
			pool["sources"].([]any)[0].(objectMap)["kind"] = "arbitrary"
		}},
		{"bad source id", func(v objectMap) {
			pool := nested(v, "purchasable_content")["synergy_pools"].([]any)[0].(objectMap)
			pool["sources"].([]any)[0].(objectMap)["id_or_class"] = "Not mechanical"
		}},
	} {
		t.Run(test.name, func(t *testing.T) {
			var value objectMap
			decoder := json.NewDecoder(bytes.NewReader(publishedArtifact(t)))
			decoder.UseNumber()
			if err := decoder.Decode(&value); err != nil {
				t.Fatal(err)
			}
			test.mutate(value)
			data, err := json.Marshal(value)
			if err != nil {
				t.Fatal(err)
			}
			before := bytes.Clone(data)
			if err := Validate(data); !errors.Is(err, ErrInvalidArtifact) {
				t.Fatalf("malformed artifact admitted: %v", err)
			}
			if !bytes.Equal(data, before) {
				t.Fatal("refusal rewrote malformed evidence")
			}
		})
	}
	for _, data := range [][]byte{[]byte(`{`), append(publishedArtifact(t), []byte(`{}`)...), {'"', 0xff, '"'}} {
		if err := Validate(data); !errors.Is(err, ErrInvalidArtifact) {
			t.Fatalf("invalid JSON bytes admitted: %q err=%v", data, err)
		}
	}
}

func TestFormulaSchemasAreValidAndFreshAcrossExports(t *testing.T) {
	first := Schemas()
	second := Schemas()
	if !reflect.DeepEqual(first, second) {
		t.Fatal("descriptor export is nondeterministic")
	}
	definitions, err := publicapi.ValidateSchemaDefinitions(first)
	if err != nil {
		t.Fatal(err)
	}
	if err := publicapi.ValidateJSON(SchemaName, publishedArtifact(t), definitions); err != nil {
		t.Fatal(err)
	}
	first[0].Schema.Fields[0].Name = "mutated"
	if !reflect.DeepEqual(second, Schemas()) {
		t.Fatal("caller mutation corrupted subsequent owner exports")
	}
}
