package garden

import (
	"encoding/json"
	"fmt"
	"strconv"
	"testing"

	"cloud-clicker/server/determinism"
)

// Compact tuples are authored literal expectations, never generated by tick/Advance.
type tickWitness struct {
	Name         string              `json:"name"`
	Level        int64               `json:"level"`
	Seq          int64               `json:"seq"`
	Ticks        int64               `json:"ticks"`
	Substrate    string              `json:"substrate"`
	Chances      []int64             `json:"chances"`
	MaturationA  *int64              `json:"maturation_a"`
	ChanceFactor *int64              `json:"chance_factor"`
	Initial      [][]json.RawMessage `json:"initial"`
	Post         [][]json.RawMessage `json:"post"`
	Matured      [][]json.RawMessage `json:"matured"`
	Spawned      [][]json.RawMessage `json:"spawned"`
}

func witnessValue[T any](t testing.TB, tuple []json.RawMessage, index int) T {
	t.Helper()
	var value T
	if index >= len(tuple) {
		t.Fatalf("short witness tuple: %s", tuple)
	}
	if err := json.Unmarshal(tuple[index], &value); err != nil {
		t.Fatal(err)
	}
	return value
}

func witnessPlots(t testing.TB, tuples [][]json.RawMessage) []Plot {
	t.Helper()
	plots := []Plot{}
	for _, tuple := range tuples {
		if len(tuple) != 5 {
			t.Fatalf("invalid plot tuple: %s", tuple)
		}
		plots = append(plots, Plot{Row: witnessValue[int64](t, tuple, 0), Col: witnessValue[int64](t, tuple, 1),
			SpeciesID: witnessValue[string](t, tuple, 2), AgeTicks: witnessValue[int64](t, tuple, 3), MaturedEffectPPM: witnessValue[*int64](t, tuple, 4)})
	}
	return plots
}

func TestGardenIndependentTickWitnesses(t *testing.T) {
	var population struct {
		Version int           `json:"version"`
		Salt    string        `json:"salt"`
		Base    string        `json:"base"`
		Draws   [][]uint64    `json:"draws"`
		Cases   []tickWitness `json:"cases"`
	}
	if err := json.Unmarshal(readRepo(t, "testdata/garden/tick-witnesses-v1.json"), &population); err != nil {
		t.Fatal(err)
	}
	if population.Version != 1 || len(population.Cases) != 16 || len(population.Draws) != 2 {
		t.Fatal("independent SG4 population changed")
	}
	t.Run("literal_PRNG_binding", func(t *testing.T) {
		if determinism.NewSplitMix64(0).Next() != 0xe220a8397b1dcdaf {
			t.Fatal("seed-zero arithmetic control")
		}
		salt, err := strconv.ParseUint(population.Salt, 16, 64)
		if err != nil {
			t.Fatal(err)
		}
		base := determinism.Substream(salt, "garden.founder.v1").Next()
		if fmt.Sprint(base) != population.Base {
			t.Fatalf("founder base = %d, want %s", base, population.Base)
		}
		for index, draws := range population.Draws {
			if len(draws) != 8 {
				t.Fatal("literal draw population changed")
			}
			rng := determinism.Substream(base^uint64(index+1), "garden.tick.v1")
			for ordinal, want := range draws {
				if got := rng.Bound(1_000_000); got != want {
					t.Fatalf("tick %d draw %d = %d, want %d", index+1, ordinal+1, got, want)
				}
			}
		}
	})
	seen := map[string]bool{}
	for _, test := range population.Cases {
		if seen[test.Name] || test.Name == "" || len(test.Chances) != 5 || test.Ticks < 1 || test.Ticks > 2 {
			t.Fatal("invalid/duplicate witness declaration")
		}
		seen[test.Name] = true
		t.Run(test.Name, func(t *testing.T) {
			ops := []fixtureOp{}
			for index, chance := range test.Chances {
				ops = append(ops, setOp(chance, "recipes", index, "chance_ppm"))
			}
			if test.MaturationA != nil {
				ops = append(ops, setOp(*test.MaturationA, "species", 0, "maturation_ticks"))
			}
			if test.ChanceFactor != nil {
				ops = append(ops, setOp(*test.ChanceFactor, "substrates", 0, "chance_factor_ppm"))
			}
			catalog := scenarioCatalog(t, ops)
			state := NewState(catalog)
			state.SaltHex, state.TickAnchorWallMS = &population.Salt, newInt64(1_000_000)
			state.TickSeq, state.SubstrateID, state.Plots = test.Seq, test.Substrate, witnessPlots(t, test.Initial)
			initial, err := EncodeState(state)
			if err != nil {
				t.Fatal(err)
			}
			state, err = DecodeState(initial)
			if err != nil || ValidateAgainst(catalog, state) != nil {
				t.Fatalf("witness must enter through real SG2 admission: %v", err)
			}
			substrate, ok := catalog.Substrate(test.Substrate)
			if !ok {
				t.Fatal("missing substrate")
			}
			at := int64(1_000_000) + test.Ticks*substrate.TickMS
			wantState := state.Clone()
			wantState.TickAnchorWallMS, wantState.TickSeq, wantState.Plots = &at, test.Seq+test.Ticks, witnessPlots(t, test.Post)
			want := Advance{TicksApplied: test.Ticks, TickSeqAfter: test.Seq + test.Ticks, Matured: []PlotRef{}, Spawned: []Spawn{}}
			for _, tuple := range test.Matured {
				want.Matured = append(want.Matured, PlotRef{Row: witnessValue[int64](t, tuple, 0), Col: witnessValue[int64](t, tuple, 1), SpeciesID: witnessValue[string](t, tuple, 2)})
			}
			for _, tuple := range test.Spawned {
				want.Spawned = append(want.Spawned, Spawn{Row: witnessValue[int64](t, tuple, 0), Col: witnessValue[int64](t, tuple, 1), SpeciesID: witnessValue[string](t, tuple, 2), RecipeID: witnessValue[string](t, tuple, 3)})
			}
			if err := ValidateAgainst(catalog, wantState); err != nil {
				t.Fatalf("literal expected state outside contract: %v", err)
			}
			got, err := catalog.Advance(state, AdvanceInput{ServerMS: at, HostLevel: test.Level, Unlocked: true})
			if err != nil {
				t.Fatal(err)
			}
			gotBytes, _ := json.Marshal(got)
			wantBytes, _ := json.Marshal(want)
			if string(gotBytes) != string(wantBytes) {
				t.Fatalf("summary = %s, want %s", gotBytes, wantBytes)
			}
			gotState, err := EncodeState(state)
			if err != nil || ValidateAgainst(catalog, state) != nil {
				t.Fatalf("output outside SG2: %v", err)
			}
			wantBytes, err = EncodeState(wantState)
			if err != nil || string(gotState) != string(wantBytes) {
				t.Fatalf("post = %s, want %s (err=%v)", gotState, wantBytes, err)
			}
		})
	}
}
